pipeline {

agent any

tools {

 maven "Maven 3.6.1"
}
    stages {
        stage("build") {
            steps {
            echo 'Building worker app'
	    dir ('worker') {
	    sh 'mvn compile'
        }
    }
    stage("test") {
            steps {
            echo 'Testing worker'
        }
    }
    stage("three") {
            steps {
            echo 'Welcome to hell World'
        }
    }
}
post {
    always {
        echo 'this is a post action'
    }
}
}

