pipeline {

agent any

tools {

 maven "Maven 3.6.1"
}
    stages {
        stage("build") {
            steps {
            echo 'Building worker app'
	    dir ('worker') {
	    sh 'mvn compile'
        }
    }
}
    stage("test") {
            steps {
            echo 'Testing worker app'
	    dir ('worker') {
	    sh 'mvn clean test'
}
        }
    }
    stage("three") {
            steps {
            echo 'Packaging worker app'
  	    dir ('worker') {
	    sh 'mvn package -D skipTests'
        }
    }
}
}
post {
    always {
    archiveArtifacts '**/worker/target/*.jar'}
}
}

